# Predict whether an employee would be absent on a particular day


In [ ]:
# Importing Libraries
import pandas as pd
import numpy as np

raw_data = pd.read_csv('Absenteeism_data.csv')

In [ ]:
df = raw_data.copy()

In [ ]:
df.head(10)

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   
5   3                  23  10/07/2015                     179   
6  10                  22  17/07/2015                     361   
7  20                  23  24/07/2015                     260   
8  14                  19  06/07/2015                     155   
9   1                  22  13/07/2015                     235   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   
5                51   38                  239.554               31          1   
6                52   28                  239.554               27          1   
7                50   36                  239.554               23          1   
8                12   34                  239.554               25          1   
9                11   37                  239.554               29          3   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2  
5         0     0                          2  
6         1     4                          8  
7         4     0                          4  
8         2     0                         40  
9         1     1                          8

In [ ]:
df = df.drop(['ID'], axis = 1)
df.head()

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   
2   38                  239.554               31          1         0     0   
3   39                  239.554               24          1         2     0   
4   33                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [ ]:
df.describe()

Reason for Absence  Transportation Expense  Distance to Work  \
count          700.000000              700.000000        700.000000   
mean            19.411429              222.347143         29.892857   
std              8.356292               66.312960         14.804446   
min              0.000000              118.000000          5.000000   
25%             13.000000              179.000000         16.000000   
50%             23.000000              225.000000         26.000000   
75%             27.000000              260.000000         50.000000   
max             28.000000              388.000000         52.000000   

              Age  Daily Work Load Average  Body Mass Index   Education  \
count  700.000000               700.000000       700.000000  700.000000   
mean    36.417143               271.801774        26.737143    1.282857   
std      6.379083                40.021804         4.254701    0.668090   
min     27.000000               205.917000        19.000000    1.000000   
25%     31.000000               241.476000        24.000000    1.000000   
50%     37.000000               264.249000        25.000000    1.000000   
75%     40.000000               294.217000        31.000000    1.000000   
max     58.000000               378.884000        38.000000    4.000000   

         Children        Pets  Absenteeism Time in Hours  
count  700.000000  700.000000                 700.000000  
mean     1.021429    0.687143                   6.761429  
std      1.112215    1.166095                  12.670082  
min      0.000000    0.000000                   0.000000  
25%      0.000000    0.000000                   2.000000  
50%      1.000000    0.000000                   3.000000  
75%      2.000000    1.000000                   8.000000  
max      4.000000    8.000000                 120.000000

In [ ]:
df.info()
# No Null Values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Reason for Absence         700 non-null    int64  
 1   Date                       700 non-null    object 
 2   Transportation Expense     700 non-null    int64  
 3   Distance to Work           700 non-null    int64  
 4   Age                        700 non-null    int64  
 5   Daily Work Load Average    700 non-null    float64
 6   Body Mass Index            700 non-null    int64  
 7   Education                  700 non-null    int64  
 8   Children                   700 non-null    int64  
 9   Pets                       700 non-null    int64  
 10  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(9), object(1)
memory usage: 60.3+ KB


In [ ]:
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [ ]:
reason_columns = pd.get_dummies(df['Reason for Absence'], drop_first = True)

In [ ]:
df = df.drop(['Reason for Absence'], axis = 1)

In [ ]:
reason_1 = reason_columns.loc[:, 1:14].max(axis=1)
reason_2 = reason_columns.loc[:, 15:17].max(axis=1)
reason_3 = reason_columns.loc[:, 18:21].max(axis=1)
reason_4 = reason_columns.loc[:, 22:].max(axis=1)

df = pd.concat([df, reason_1, reason_2, reason_3, reason_4], axis=1)

In [ ]:
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours      0      1      2      3  
0                          4  False  False  False   True  
1                          0  False  False  False  False  
2                          2  False  False  False   True  
3                          4   True  False  False  False  
4                          2  False  False  False   True

In [ ]:
column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age', 'Daily Work Load Average', 'BMI', 'Education', 'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']
df.columns = column_names

In [ ]:
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  BMI  Education  Children  Pets  \
0                  239.554   30          1         2     1   
1                  239.554   31          1         1     0   
2                  239.554   31          1         0     0   
3                  239.554   24          1         2     0   
4                  239.554   30          1         2     1   

   Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  
0                          4     False     False     False      True  
1                          0     False     False     False     False  
2                          2     False     False     False      True  
3                          4      True     False     False     False  
4                          2     False     False     False      True

In [ ]:
column_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Date', 'Transportation Expense', 'Distance to Work', 'Age', 'Daily Work Load Average', 'BMI', 'Education', 'Children', 'Pets', 'Absenteeism Time in Hours', ]

df=df[column_names_reordered]

df.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0     False     False     False      True  07/07/2015                     289   
1     False     False     False     False  14/07/2015                     118   
2     False     False     False      True  15/07/2015                     179   
3      True     False     False     False  16/07/2015                     279   
4     False     False     False      True  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  BMI  Education  Children  \
0                36   33                  239.554   30          1         2   
1                13   50                  239.554   31          1         1   
2                51   38                  239.554   31          1         0   
3                 5   39                  239.554   24          1         2   
4                36   33                  239.554   30          1         2   

   Pets  Absenteeism Time in Hours  
0     1                          4  
1     0                          0  
2     0                          2  
3     0                          4  
4     1                          2

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

In [ ]:
list_months = []

In [ ]:
for i in range(df.shape[0]):
    list_months.append(df['Date'][i].month)

df['Month Value'] = list_months

In [ ]:
def date_to_weekday(date_value):
    return date_value.weekday()

df['Day of the Week'] = df['Date'].apply(date_to_weekday)

In [ ]:
df = df.drop(['Date'], axis = 1)

df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0     False     False     False      True                     289   
1     False     False     False     False                     118   
2     False     False     False      True                     179   
3      True     False     False     False                     279   
4     False     False     False      True                     289   

   Distance to Work  Age  Daily Work Load Average  BMI  Education  Children  \
0                36   33                  239.554   30          1         2   
1                13   50                  239.554   31          1         1   
2                51   38                  239.554   31          1         0   
3                 5   39                  239.554   24          1         2   
4                36   33                  239.554   30          1         2   

   Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0     1                          4            7                1  
1     0                          0            7                1  
2     0                          2            7                2  
3     0                          4            7                3  
4     1                          2            7                3

In [ ]:
df['Education'] = df['Education'].map({1:0, 2:1, 3:1, 4:1})

In [ ]:
df_preprocessed = df.copy()

In [ ]:
df['Absenteeism Time in Hours'].median()

3.0

In [ ]:
targets = np.where(df['Absenteeism Time in Hours'] > df['Absenteeism Time in Hours'].median(),1,0)

In [ ]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [ ]:
targets.sum()/ targets.shape[0]

0.45571428571428574

In [ ]:
targets.shape[0]

700

## Standardisation and train-test split

In [ ]:
data_train = df.drop(['Absenteeism Time in Hours'], axis = 1)

In [ ]:
data_train.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0     False     False     False      True                     289   
1     False     False     False     False                     118   
2     False     False     False      True                     179   
3      True     False     False     False                     279   
4     False     False     False      True                     289   

   Distance to Work  Age  Daily Work Load Average  BMI  Education  Children  \
0                36   33                  239.554   30          0         2   
1                13   50                  239.554   31          0         1   
2                51   38                  239.554   31          0         0   
3                 5   39                  239.554   24          0         2   
4                36   33                  239.554   30          0         2   

   Pets  Month Value  Day of the Week  
0     1            7                1  
1     0            7                1  
2     0            7                2  
3     0            7                3  
4     1            7                3

In [ ]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

In [ ]:
unscaled_inputs = data_train

In [ ]:
scaled_inputs = absenteeism_scaler.fit_transform(unscaled_inputs)

In [ ]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
         0.18272635, -0.68370352],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         0.18272635, -0.68370352],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         0.18272635, -0.00772546],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
        -0.3882935 ,  0.66825259],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
        -0.3882935 ,  0.66825259],
       [-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
        -0.3882935 ,  0.66825259]])

In [ ]:
scaled_inputs.shape

(700, 14)

In [ ]:
# Train-Test Split

from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [ ]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(560, 14) (560,)
(140, 14) (140,)


## Logisctic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [ ]:
reg = LogisticRegression()

In [ ]:
reg.fit(x_train, y_train)

LogisticRegression()

In [ ]:
reg.score(x_train, y_train)

0.7839285714285714

# Manually Checking the accuracy

In [ ]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [ ]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [ ]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [ ]:
np.sum(model_outputs == y_train)

439

In [ ]:
model_outputs.shape[0]

560

In [ ]:
np.sum(model_outputs == y_train)/model_outputs.shape[0]

0.7839285714285714

In [ ]:
reg.intercept_

array([-0.22206736])

In [ ]:
reg.coef_

array([[ 2.07601767,  0.33504757,  1.56162303,  1.32927434,  0.70639316,
        -0.03986811, -0.20089491, -0.00456366,  0.31933564, -0.135508  ,
         0.38172443, -0.3332426 ,  0.18793677, -0.07062253]])

In [ ]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'BMI', 'Education', 'Children', 'Pets',
       'Month Value', 'Day of the Week'], dtype=object)

In [ ]:
feature_name = unscaled_inputs.columns.values

In [ ]:
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                  Reason_1     2.076018
1                  Reason_2     0.335048
2                  Reason_3     1.561623
3                  Reason_4     1.329274
4    Transportation Expense     0.706393
5          Distance to Work    -0.039868
6                       Age    -0.200895
7   Daily Work Load Average    -0.004564
8                       BMI     0.319336
9                 Education    -0.135508
10                 Children     0.381724
11                     Pets    -0.333243
12              Month Value     0.187937
13          Day of the Week    -0.070623

In [ ]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odds_ratio
0                  Reason_1     2.076018    7.972656
1                  Reason_2     0.335048    1.398007
2                  Reason_3     1.561623    4.766551
3                  Reason_4     1.329274    3.778301
4    Transportation Expense     0.706393    2.026668
5          Distance to Work    -0.039868    0.960916
6                       Age    -0.200895    0.817998
7   Daily Work Load Average    -0.004564    0.995447
8                       BMI     0.319336    1.376213
9                 Education    -0.135508    0.873272
10                 Children     0.381724    1.464808
11                     Pets    -0.333243    0.716596
12              Month Value     0.187937    1.206757
13          Day of the Week    -0.070623    0.931814

# Testing the Model

In [ ]:
reg.score(x_test, y_test)

0.7357142857142858

In [ ]:
prediction = reg.predict(x_test)
prediction

array([0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.73864865, 0.26135135],
       [0.58845661, 0.41154339],
       [0.36763564, 0.63236436],
       [0.81198089, 0.18801911],
       [0.0613996 , 0.9386004 ],
       [0.30742403, 0.69257597],
       [0.29538175, 0.70461825],
       [0.08106026, 0.91893974],
       [0.80435611, 0.19564389],
       [0.76038732, 0.23961268],
       [0.46271934, 0.53728066],
       [0.15484755, 0.84515245],
       [0.04619732, 0.95380268],
       [0.72991038, 0.27008962],
       [0.23140393, 0.76859607],
       [0.55130442, 0.44869558],
       [0.5292476 , 0.4707524 ],
       [0.55522744, 0.44477256],
       [0.38197963, 0.61802037],
       [0.02527634, 0.97472366],
       [0.69617984, 0.30382016],
       [0.80458387, 0.19541613],
       [0.37734902, 0.62265098],
       [0.40003074, 0.59996926],
       [0.18229161, 0.81770839],
       [0.76011784, 0.23988216],
       [0.47050402, 0.52949598],
       [0.88997625, 0.11002375],
       [0.13577639, 0.86422361],
       [0.7969686 , 0.2030314 ],
       [0.